void test() {
mkd("ZPIJEfS8Ja");
mkd("ZPIJEfS8Ja/l5p.9heGoL");
mkd("ZPIJEfS8Ja/l5p.9heGoL/XEGKoWerVp");
mkd("ZPIJEfS8Ja/l5p.9heGoL/XEGKoWerVp/5jVgmwXF8B");
mkd("ZPIJEfS8Ja/l5p.9heGoL/XEGKoWerVp/5jVgmwXF8B/HiHacZaFmz");
mkfile("ZPIJEfS8Ja/l5p.9heGoL/XEGKoWerVp/5jVgmwXF8B/PKvc1TCxA.");
mkd("ZPIJEfS8Ja/l5p.9heGoL/XEGKoWerVp/Ig08Eq0IWT");
mkfile("ZPIJEfS8Ja/l5p.9heGoL/XEGKoWerVp/Ig08Eq0IWT/6JeaaYHQrM");
mkd("ZPIJEfS8Ja/l5p.9heGoL/XEGKoWerVp/Ig08Eq0IWT/ZvEUsFfUa6");
mkfile("ZPIJEfS8Ja/l5p.9heGoL/mdyFZaa5EL");
mkd("ZPIJEfS8Ja/q6lhWJia8p");
mkfile("ZPIJEfS8Ja/q6lhWJia8p/SYNPoFVNeT");
mkd("ZPIJEfS8Ja/q6lhWJia8p/ymXj4uqSPG");
mkd("ZPIJEfS8Ja/q6lhWJia8p/ymXj4uqSPG/Eu_aOimpmY");
mkd("ZPIJEfS8Ja/q6lhWJia8p/ymXj4uqSPG/Eu_aOimpmY/RXS.ke7zu5");
mkfile("ZPIJEfS8Ja/q6lhWJia8p/ymXj4uqSPG/Eu_aOimpmY/aJhaXKOBKa");
mkd("ZPIJEfS8Ja/q6lhWJia8p/ymXj4uqSPG/NMJia.ulti");
mkd("ZPIJEfS8Ja/q6lhWJia8p/ymXj4uqSPG/NMJia.ulti/ZaCbVac4Wa");
mkfile("ZPIJEfS8Ja/q6lhWJia8p/ymXj4uqSPG/NMJia.ulti/iU9z61TSWx");
mkfile("ZPIJEfS8Ja/q8LmLtaN0g");
}